version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.8
    commands:
      - echo Install started on `date`
      - make install
  pre_build:
    commands:
      - echo Pre-build started on `date`
      - make pre_build
  build:
    commands:
      - echo Build started on `date`
      - make build
  post_build:
    commands:
      - echo Post-build started on `date`
      - make post_build
artifacts:
  files:
    - '**/*'

